trio-asyncio no longer applies a limit to the maximum number of
asyncio callbacks (including new task creations) that can be enqueued
near-simultaneously. Previously the default limit was 10,000. A limit
may still be requested using the *queue_len* parameter to
:func:`open_loop`, but this is discouraged because there is no way
to fail gracefully upon exceeding the limit; it will most likely just
crash your program.
